version: '3.6'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file: configuration.env
    volumes:
      - ./mysql/db.cnf:/etc/mysql/conf.d/db.cnf
      - ./slow.log:/var/log/mysql/mysql-slow.log
      - db:/var/lib/mysql
    networks:
      - application

  mongodb:
    image: mongo:4.2
    container_name: mongo
    volumes:
      - mongo:/data/db
    networks:
      - application

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:9000"
    env_file: configuration.env
    working_dir: /var/www
    volumes:
      - ./php:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - application

  filebeat:
    build:
      context: filebeat/
    container_name: filebeat
    depends_on:
      - mysql
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./slow.log:/var/log/mysql/mysql-slow.log
      - filebeat:/usr/share/filebeat/data/
    networks:
      - application

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - application

  logstash:
    build:
      context: logstash/
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - application
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    ports:
      - "5601:5601"
    networks:
      - application
    depends_on:
      - elasticsearch

  graylog:
    image: graylog/graylog:4.3
    container_name: graylog
    volumes:
      - graylog:/usr/share/graylog/data
      - ./plugin:/usr/share/graylog/plugin
    environment:
      - GRAYLOG_PASSWORD_SECRET=password
      - GRAYLOG_ROOT_PASSWORD_SHA2=5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8 #password
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 -- /docker/entrypoint.sh
    links:
      - mongodb:mongo
      - elasticsearch
      - mysql
    depends_on:
      - mongodb
      - elasticsearch
      - mysql
    ports:
      - "9000:9000"
      - "5044:5044"
    networks:
      - application

networks:
  application:
    driver: bridge

volumes:
  elasticsearch:
    driver: local
  db:
    driver: local
  graylog:
    driver: local
  mongo:
    driver: local
  filebeat:
    driver: local